### ISSUE TITLE
[Revamp] Call for UI/UX designers

### ISSUE THREAD

**Issue by mazipan** [mazipan/quran-offline#50]
This project is developed by myself and designed by my opinion.
Need help from a UI/UX designer to revamp the whole experience to be better.

Q: Are you will get paid for this task?
A: No, it's free.
Q: What you will get for designing this app?
A: You will get free publication for your work.
Q: Can I have a credit title?
A: Sure, you will get it. I will proud to put your name in this App and project.

**Comment by muhammadridho** [comment]
Hi, mas irfan. can you list what icon you want to make ?

**Comment by mazipan** [comment]
Can you try to use this web app first @muhammadridho ?
I open for full app revamp, because I know I am not good in designing user journey experience.
Just give me an input from your side.

**Comment by mazipan** [comment]
This issue for revamping the full user journey, see #51 for Icon revamping

**Comment by jotasprout** [comment]
I would like to help. Just starting to use it tonight.
