### ISSUE TITLE
[Revamp] Call for Icon Designer

### ISSUE THREAD

**Issue by mazipan** [mazipan/quran-offline#51]
This icon is generated in canva, need better icon to this App.

https://github.com/mazipan/quran-offline/blob/master/static/icon-192x192.png

Q: Are you will get paid for this task?
A: No, it's free.
Q: What you will get for designing icon for this app?
A: You will get free publication for your work.
Q: Can I have a credit title?
A: Sure, you will get it. I will proud to put your name in this App and project.

**Comment by hackidozone** [comment]
the final output if i want help to design is svg or what mas @mazipan?

thanks

**Comment by mazipan** [comment]
I like SVG for icon, but if you cn provide various version it will better
